### ISSUE TITLE
The AR Path matching can not handle some schematics

### ISSUE THREAD

**Issue by JLCPCB** [essele/kicad_jlcpcba#2]
Hi,

This plugin is neat.

I tested it in Windows 7 (KiCad 5.1.7) and Ubuntu 18.04 (KiCad 5.1.8) with the following projects (Both use hierarchy schematics):

* KiCad demo project video
* https://github.com/joshtyler/manila-ice

KiCad output KeyError: 'reference'

I tracked the code and found that the problem is here:

```python
        # There are two ways to find a reference. If we have no spath then
        # we use the "F 0" field, otherwise we look for an AR Path that matches
        if (spath):
            # The AR Path version...
            m = re.match('^AR Path="([^"]+)" Ref="([^"]+)".*', line)
            if (m):
                if (m.group(1).startswith(spath)):
                    item['reference'] = m.group(2)
                    item['uid'] = m.group(1)
                continue
        else:
            # The normal version...
            m = re.match('^F 0 "([^"]+)"', line)
            if (m):
                item['reference'] = m.group(1)
                continue
```

For example, with the video project, when read_sch.py find that it needs to go to muxdata.sch from video.sch,
it carry a true value for spath ("/4BF0367D"), but in muxdata.sch there's no AR Path pattern, so it does not match
and the else statement will not be executed too. So there's no 'reference' key in item.

The good thing of this plugin is the user don't need to generate a fresh netlist to get the BOM every time as it parse the schematics directly.

But KiCad has python library for Eeschema to get the BOM easily, so I wonder if there's another easier method to get the BOM from schematic source file.

--
Best Regards,
Atommann
Technical Writer and Layout Engineer from JLCPCB

**Comment by essele** [comment]
Hi Atommann,

Thanks for highlighting this. I’m obviously keen that this plugin is as useful as possible …. I don’t really know how many people are using it, but I use it for all of my boards!

I’m just looking at the problem now … there seems to be a different approach for a nested sheet that’s used only once vs. a nested sheet used multiple times (the latter being the situation I had and coded for, so I need to build a couple of test cases to figure this out. Hopefully should be resolved today.

On the eeschema BOM api … I did look at the python library, there was a reason I didn’t use it, but I really can’t remember why … I’ll have another look.

Thanks,

Lee.

**Comment by essele** [comment]
Hi Atommann,

I’ve committed a fix which seems to work … could you test and see if it works for you.

The issue was that for a sheet that’s used multiple times there are “AR Path” values in the sheet that map to the different reference names for each use, I had assumed this was always the case for nested sheets. But if a sheet is only used once then these don’t exist and the standard naming is used.

Lee.

**Comment by JLCPCB** [comment]
Hi Lee,

Thanks for the prompt reply.
I was confused by the AR Path stuff :)
I'll test the code.

--
Atommann
