### ISSUE TITLE
AttributeError: 'BOARD' object has no attribute 'GetModules'

### ISSUE THREAD

**Issue by AiGreek** [essele/kicad_jlcpcba#9]
I wanted to try this plugin with the last nightly version of Kicad. Files are generated but are empty.

> Version: (5.99.0-10447-gf083f043cb), release build
> Platform: Windows 10 (build 19042), 64-bit edition, 64 bit, Little endian, wxMSW

and i have this error in the log file: 

> Traceback (most recent call last):
>   File "C:/Users/Trajectory/Documents/KiCad/5.99/scripting\plugins\kicad_jlcpcba\jlcpcba_action.py", line 21, in Run
>     create_pcba()
>   File "C:/Users/Trajectory/Documents/KiCad/5.99/scripting\plugins\kicad_jlcpcba\jlcpcba_main.py", line 110, in create_pcba
>     for m in board.GetModules():
> AttributeError: 'BOARD' object has no attribute 'GetModules'

**Comment by essele** [comment]
Hi,

This plugin isn’t developed against the nightly builds (as I don’t use them) … I will get around to looking at it, but haven’t had a chance yet.

There are some changes proposed by hildogjr (check the pull request) which you may be able to apply, but I haven’t tested them yet.

Cheers,

Lee.

**Comment by AiGreek** [comment]
Thanks, works perfectly now :)
